import { Component, ElementRef, ViewChild, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable, of, switchMap } from 'rxjs';
import { AdminApiService } from '../core/admin-api.service';
import { AdminTechnology } from '../core/admin-api.models';

type Section = 'projects' | 'articles' | 'technologies' | 'skills' | 'timeline';

@Component({
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    <section class="heading"><p class="eyebrow">Administration / {{ labels[section] }}</p><h1>{{ labels[section] }}</h1><p>Modifier les données publiques sans quitter le même espace de travail.</p></section>
    <div class="workspace">
      <section class="list-panel"><div class="panel-heading"><h2>Contenus enregistrés</h2><button type="button" class="secondary" (click)="startCreate()">Nouveau</button></div>
        @if (loading) {<p>Chargement…</p>} @else if (!items.length) {<p class="empty">Aucun contenu enregistré.</p>} @else {<div class="records">@for (item of items; track item.id) {<article><div><strong>{{ item.title || item.name }}</strong><span>{{ summary(item) }}</span></div><div class="actions"><button type="button" (click)="edit(item)">Modifier</button><button type="button" class="danger" (click)="remove(item)">Supprimer</button></div></article>}</div>}
      </section>
      <section class="form-panel"><p class="eyebrow">{{ editingId ? 'Modifier' : 'Créer' }}</p><h2>{{ editingId ? 'Mettre à jour le contenu' : 'Ajouter un contenu' }}</h2>
        <form [formGroup]="form" (ngSubmit)="save()">
          <label for="title">{{ section === 'technologies' || section === 'skills' ? 'Nom' : 'Titre' }}</label><input id="title" formControlName="title">
          <label for="description">Description / résumé</label><textarea id="description" rows="4" formControlName="description"></textarea>
          @if (section === 'projects') {
            <label for="githubUrl">URL du dépôt</label><input id="githubUrl" formControlName="githubUrl" type="url">
            <label for="technologyIds">Technologies (IDs séparés par des virgules)</label><input id="technologyIds" formControlName="technologyIds" placeholder="1, 2">
            <label for="projectImage">Illustration</label><input id="projectImage" type="file" accept="image/*" (change)="selectImage($event)">
            <label class="check"><input type="checkbox" formControlName="featured"> Afficher sur la page d’accueil</label>
          }
          @if (section === 'articles') {
             <label for="content">Contenu Markdown</label><textarea #contentInput id="content" rows="10" formControlName="content"></textarea>
             <fieldset class="illustration-fieldset"><legend>Illustration inline</legend><label for="articleIllustration">Image</label><input #illustrationInput id="articleIllustration" type="file" accept="image/png,image/jpeg,image/webp" (change)="selectIllustration($event)"><label for="illustrationAlt">Texte alternatif</label><input id="illustrationAlt" formControlName="illustrationAlt" placeholder="Architecture du système"><label for="illustrationCaption">Légende (optionnelle)</label><input id="illustrationCaption" formControlName="illustrationCaption" placeholder="Architecture générale du workflow"><button type="button" class="secondary" (click)="uploadIllustration()" [disabled]="illustrationUploading || !selectedIllustrationFile || !form.controls.illustrationAlt.value.trim()">{{ illustrationUploading ? 'Téléversement…' : 'Téléverser et insérer' }}</button>@if (illustrationMessage) {<p class="success" role="status">{{ illustrationMessage }}</p>}<small>PNG, JPEG ou WebP, 5 Mo maximum. Le texte alternatif est obligatoire.</small></fieldset>
            <label for="tags">Tags séparés par des virgules</label><input id="tags" formControlName="tags" placeholder="java, spring">
            <fieldset class="cover-fieldset"><legend>Image de couverture</legend><input #coverInput id="articleCover" type="file" accept="image/png,image/jpeg,image/webp" (change)="selectCover($event)">@if (coverPreview(); as preview) {<img class="cover-preview" [src]="preview" alt="Aperçu de la couverture de l’article">}@if (currentCover || selectedCoverFile) {<button type="button" class="secondary cover-remove" (click)="removeCover()">{{ selectedCoverFile ? 'Retirer la sélection' : 'Supprimer la couverture' }}</button>}<small>PNG, JPEG ou WebP, 5 Mo maximum.</small></fieldset>
            <label class="check"><input type="checkbox" formControlName="published"> Publier immédiatement</label>
          }
          @if (section === 'technologies') {<label for="iconUrl">URL de l’icône</label><input id="iconUrl" formControlName="iconUrl">}
          @if (section === 'skills') {<label for="category">Catégorie</label><select id="category" formControlName="category">@for (category of categories; track category) {<option [value]="category">{{ category }}</option>}</select><label for="skillLevel">Niveau</label><select id="skillLevel" formControlName="skillLevel">@for (level of levels; track level) {<option [value]="level">{{ level }}</option>}</select>}
          @if (section === 'timeline') {<label for="date">Date</label><input id="date" formControlName="date"><label for="link">Lien</label><input id="link" formControlName="link" type="url"><label for="displayOrder">Ordre d’affichage</label><input id="displayOrder" formControlName="displayOrder" type="number"><label for="type">Type</label><select id="type" formControlName="type">@for (timelineType of timelineTypes; track timelineType) {<option [value]="timelineType">{{ timelineType }}</option>}</select>}
          <p class="error" role="alert">{{ error }}</p><button type="submit" [disabled]="form.invalid || saving">{{ saving ? 'Enregistrement…' : 'Enregistrer' }}</button>
        </form>
      </section>
    </div>
  `,
  styles: `
    .heading { max-width:700px; padding:3rem 0 2rem; } .eyebrow { color:var(--accent); font:var(--type-xs) var(--font-mono); letter-spacing:.08em; text-transform:uppercase; } h1 { margin:.7rem 0 1rem; font-family:var(--font-display); font-size:clamp(3rem,6vw,5.4rem); font-weight:500; line-height:.95; letter-spacing:-.06em; } .heading > p:last-child { color:var(--muted); } .workspace { display:grid; grid-template-columns:minmax(0,1.2fr) minmax(300px,.8fr); gap:1rem; align-items:start; } .list-panel, .form-panel { min-width:0; padding:1.25rem; border:1px solid var(--line); border-radius:var(--radius-md); } .form-panel { position:sticky; top:1rem; background:var(--color-slate); } .panel-heading { display:flex; justify-content:space-between; align-items:center; gap:1rem; } h2 { margin:.3rem 0 1rem; font-family:var(--font-display); font-size:1.8rem; font-weight:500; } button { padding:.65rem .8rem; color:#07101e; background:var(--accent); border:0; border-radius:var(--radius-sm); font:inherit; font-weight:800; cursor:pointer; } button:disabled { opacity:.5; cursor:not-allowed; } button.secondary { color:var(--color-text); background:transparent; border:1px solid var(--line); } button.danger { color:#ffb0b0; background:transparent; border:1px solid #65343d; } .records { display:grid; } .records article { display:flex; justify-content:space-between; align-items:center; gap:1rem; padding:1rem 0; border-top:1px solid var(--line); } .records article > div:first-child { min-width:0; display:grid; gap:.3rem; } .records strong { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; } .records span, .empty { color:var(--muted); font-size:.85rem; } .actions { display:flex; flex-shrink:0; gap:.4rem; } .actions button { padding:.4rem .55rem; font-size:.8rem; } form { display:grid; gap:.55rem; } label { margin-top:.45rem; font-size:.82rem; font-weight:700; } input, textarea, select { width:100%; box-sizing:border-box; padding:.7rem .75rem; color:var(--color-text); background:var(--color-bg); border:1px solid var(--line); border-radius:var(--radius-sm); font:inherit; } textarea { resize:vertical; } .cover-fieldset { display:grid; gap:.55rem; margin:1rem 0 0; padding:.8rem; border:1px solid var(--line); border-radius:var(--radius-sm); } .cover-fieldset legend { padding:0 .3rem; font-size:.82rem; font-weight:700; } .cover-preview { display:block; width:100%; max-height:180px; object-fit:cover; border:1px solid var(--line); border-radius:var(--radius-sm); } .cover-fieldset small { color:var(--muted); } .cover-remove { justify-self:start; } .check { display:flex; gap:.5rem; align-items:center; font-weight:500; } .check input { width:auto; } .error { min-height:1.2rem; color:#ff9c9c; font-size:.85rem; } .form-actions { display:flex; gap:.5rem; margin-top:.8rem; } @media (max-width:900px) { .workspace { grid-template-columns:1fr; } .form-panel { position:static; } } @media (max-width:560px) { .records article { align-items:flex-start; flex-direction:column; } }
  `,
})
export class AdminWorkspacePage {
  private readonly api = inject(AdminApiService);
  private readonly route = inject(ActivatedRoute);
  private readonly fb = inject(FormBuilder);
  @ViewChild('coverInput') private coverInput?: ElementRef<HTMLInputElement>;
  @ViewChild('contentInput') private contentInput?: ElementRef<HTMLTextAreaElement>;
  @ViewChild('illustrationInput') private illustrationInput?: ElementRef<HTMLInputElement>;

  protected section: Section = 'projects';
  protected items: any[] = [];
  protected editingId: number | string | null = null;
  protected selectedImage: File | null = null;
  protected selectedCoverFile: File | null = null;
  protected currentCover: string | null = null;
  protected coverBeforeRemoval: string | null = null;
  protected selectedCoverPreview: string | null = null;
  protected removeCoverRequested = false;
  protected selectedIllustrationFile: File | null = null;
  protected illustrationUploading = false;
  protected illustrationMessage = '';
  protected loading = false;
  protected saving = false;
  protected error = '';
  protected readonly labels: Record<Section, string> = { projects: 'Projets', articles: 'Articles', technologies: 'Technologies', skills: 'Compétences', timeline: 'Parcours' };
  protected readonly categories = ['BACKEND', 'FRONTEND', 'DEVOPS'];
  protected readonly levels = ['DEBUTANT', 'INTERMEDIAIRE', 'CONFIRME'];
  protected readonly timelineTypes = ['EDUCATION', 'CERTIFICATION', 'PROJECT', 'EXPERIENCE'];
  protected form = this.fb.nonNullable.group({ title: ['', Validators.required], description: [''], githubUrl: [''], technologyIds: [''], content: [''], tags: [''], illustrationAlt: [''], illustrationCaption: [''], published: [false], featured: [false], iconUrl: [''], category: ['BACKEND'], skillLevel: ['DEBUTANT'], date: [''], link: [''], displayOrder: [0], type: ['PROJECT'] });

  constructor() { this.route.paramMap.subscribe((params) => { this.section = (params.get('section') as Section) || 'projects'; this.startCreate(); this.load(); }); }
  protected load(): void { this.loading = true; this.request().subscribe({ next: (items) => { this.items = items; this.loading = false; }, error: (error) => { this.error = this.messageFor(error); this.loading = false; } }); }
  protected startCreate(): void { this.editingId = null; this.selectedImage = null; this.resetCoverState(); this.resetIllustrationState(); this.error = ''; this.form.reset({ title: '', description: '', githubUrl: '', technologyIds: '', content: '', tags: '', illustrationAlt: '', illustrationCaption: '', published: false, featured: false, iconUrl: '', category: 'BACKEND', skillLevel: 'DEBUTANT', date: '', link: '', displayOrder: 0, type: 'PROJECT' }); }
  protected selectImage(event: Event): void { this.selectedImage = (event.target as HTMLInputElement).files?.[0] ?? null; }
  protected selectCover(event: Event): void { this.revokeCoverPreview(); this.selectedCoverFile = (event.target as HTMLInputElement).files?.[0] ?? null; this.removeCoverRequested = false; this.selectedCoverPreview = this.selectedCoverFile ? URL.createObjectURL(this.selectedCoverFile) : null; }
  protected selectIllustration(event: Event): void { this.selectedIllustrationFile = (event.target as HTMLInputElement).files?.[0] ?? null; this.illustrationMessage = ''; }
  protected edit(item: any): void { this.resetCoverState(); this.resetIllustrationState(); this.editingId = item.id; this.currentCover = item.coverImage || null; this.form.patchValue({ title: item.title || item.name || '', description: item.description || item.excerpt || '', githubUrl: item.githubUrl || '', technologyIds: item.technologies?.map((technology: AdminTechnology) => technology.id).join(', ') || '', content: item.content || '', tags: item.tags?.join(', ') || '', published: item.published || false, featured: item.featured || false, iconUrl: item.iconUrl || '', category: item.category || 'BACKEND', skillLevel: item.skillLevel || 'DEBUTANT', date: item.date || '', link: item.link || '', displayOrder: item.displayOrder || 0, type: item.type || 'PROJECT' }); }
  protected uploadIllustration(): void { const file = this.selectedIllustrationFile; const alt = this.form.controls.illustrationAlt.value.trim(); if (!file || !alt) return; this.illustrationUploading = true; this.illustrationMessage = ''; this.error = ''; this.api.uploadArticleIllustration(file).subscribe({ next: ({ url }) => { const caption = this.form.controls.illustrationCaption.value.trim(); this.insertIllustration(this.markdownImage(url, alt, caption)); this.illustrationUploading = false; this.resetIllustrationState(); this.illustrationMessage = 'Illustration téléversée et insérée.'; }, error: (error) => { this.illustrationUploading = false; this.error = this.messageFor(error); } }); }
  protected removeCover(): void { const hasSelection = Boolean(this.selectedCoverFile); this.revokeCoverPreview(); this.selectedCoverFile = null; this.selectedCoverPreview = null; this.coverBeforeRemoval = !hasSelection && this.currentCover ? this.currentCover : null; this.removeCoverRequested = !hasSelection && Boolean(this.editingId && this.currentCover); this.currentCover = this.removeCoverRequested ? null : this.currentCover; if (this.coverInput) this.coverInput.nativeElement.value = ''; }
  protected coverPreview(): string | null { return this.selectedCoverPreview || this.currentCover; }
  protected save(): void { if (this.form.invalid) return; this.saving = true; this.error = ''; const request = this.payload(); const image = this.section === 'articles' ? this.selectedCoverFile : this.selectedImage; this.saveRequest(request, image).pipe(switchMap(() => this.removeCoverRequested && this.editingId ? this.api.removeArticleCover(String(this.editingId)) : of(null))).subscribe({ next: () => { this.saving = false; this.startCreate(); this.load(); }, error: (error) => { this.saving = false; this.restoreCoverAfterFailure(); this.error = this.messageFor(error); } }); }
  protected remove(item: any): void { if (!confirm(`Supprimer « ${item.title || item.name} » ?`)) return; this.deleteRequest(item.id).subscribe({ next: () => this.load(), error: (error) => this.error = this.messageFor(error) }); }
  protected summary(item: any): string { if (this.section === 'articles') return item.published ? 'Publié' : 'Brouillon'; if (this.section === 'projects') return `${item.technologies?.length || 0} technologies${item.featured ? ' · Page d’accueil' : ''}`; if (this.section === 'skills') return `${item.category} · ${item.skillLevel}`; if (this.section === 'timeline') return `${item.date} · ${item.type}`; return item.iconUrl || 'Technologie'; }
  private request(): Observable<any[]> { return this.section === 'projects' ? this.api.projects() : this.section === 'articles' ? this.api.articles() : this.section === 'technologies' ? this.api.technologies() : this.section === 'skills' ? this.api.skills() : this.api.timeline(); }
  private payload(): any { const value = this.form.getRawValue(); if (this.section === 'projects') return { title: value.title, description: value.description, githubUrl: value.githubUrl, technologyIds: value.technologyIds.split(',').map((id) => Number(id.trim())).filter(Boolean), featured: value.featured }; if (this.section === 'articles') return { title: value.title, excerpt: value.description, content: value.content, tags: value.tags.split(',').map((tag) => tag.trim()).filter(Boolean), published: value.published }; if (this.section === 'technologies') return { name: value.title, iconUrl: value.iconUrl }; if (this.section === 'skills') return { name: value.title, category: value.category, skillLevel: value.skillLevel }; return { title: value.title, date: value.date, description: value.description, link: value.link, displayOrder: value.displayOrder, type: value.type }; }
  private markdownImage(url: string, alt: string, caption: string): string { const escapedAlt = alt.replaceAll('\\', '\\\\').replaceAll(']', '\\]'); const escapedCaption = caption.replaceAll('\\', '\\\\').replaceAll('"', '\\"'); return caption ? `![${escapedAlt}](${url} "${escapedCaption}")` : `![${escapedAlt}](${url})`; }
  private insertIllustration(markdown: string): void { const control = this.form.controls.content; const content = control.value; const textarea = this.contentInput?.nativeElement; const start = textarea?.selectionStart ?? content.length; const end = textarea?.selectionEnd ?? start; const before = content.slice(0, start); const after = content.slice(end); const prefix = before.length === 0 || before.endsWith('\n\n') ? '' : before.endsWith('\n') ? '\n' : '\n\n'; const suffix = after.length === 0 || after.startsWith('\n\n') ? '' : after.startsWith('\n') ? '\n' : '\n\n'; const inserted = `${prefix}${markdown}${suffix}`; control.setValue(before + inserted + after); queueMicrotask(() => { const position = before.length + inserted.length; textarea?.focus(); textarea?.setSelectionRange(position, position); }); }
  private saveRequest(value: any, image: File | null): Observable<unknown> { if (this.section === 'projects') return this.editingId ? this.api.updateProject(Number(this.editingId), value, image) : this.api.createProject(value, image); if (this.section === 'articles') return this.editingId ? this.api.updateArticle(String(this.editingId), value, image) : this.api.createArticle(value, image); if (this.section === 'technologies') return this.editingId ? this.api.updateTechnology(Number(this.editingId), value) : this.api.createTechnology(value); if (this.section === 'skills') return this.editingId ? this.api.updateSkill(Number(this.editingId), value) : this.api.createSkill(value); return this.editingId ? this.api.updateTimeline(Number(this.editingId), value) : this.api.createTimeline(value); }
  private deleteRequest(id: number | string): Observable<unknown> { if (this.section === 'projects') return this.api.deleteProject(Number(id)); if (this.section === 'articles') return this.api.deleteArticle(String(id)); if (this.section === 'technologies') return this.api.deleteTechnology(Number(id)); if (this.section === 'skills') return this.api.deleteSkill(Number(id)); return this.api.deleteTimeline(Number(id)); }
  private resetCoverState(): void { this.revokeCoverPreview(); this.selectedCoverFile = null; this.selectedCoverPreview = null; this.currentCover = null; this.coverBeforeRemoval = null; this.removeCoverRequested = false; if (this.coverInput) this.coverInput.nativeElement.value = ''; }
  private resetIllustrationState(): void { this.selectedIllustrationFile = null; this.illustrationMessage = ''; if (this.illustrationInput) this.illustrationInput.nativeElement.value = ''; this.form.controls.illustrationAlt.setValue(''); this.form.controls.illustrationCaption.setValue(''); }
  private restoreCoverAfterFailure(): void { if (this.coverBeforeRemoval) this.currentCover = this.coverBeforeRemoval; this.coverBeforeRemoval = null; this.removeCoverRequested = false; }
  private revokeCoverPreview(): void { if (this.selectedCoverPreview) URL.revokeObjectURL(this.selectedCoverPreview); }
  private messageFor(error: any): string { const backendMessage = typeof error?.error?.message === 'string' ? error.error.message : typeof error?.error === 'string' && error.error.length < 300 ? error.error : ''; return backendMessage || (error?.status === 400 ? 'Vérifiez les champs obligatoires.' : 'Enregistrement impossible.'); }
}
